//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class Autore
    {
        public int ID { get; set; }

        [Required(ErrorMessage = "El apellido es Obligatorio!!!")]
        public string Apellido { get; set; }

        public string Nombre { get; set; }

        public Nullable<System.DateTime> FechaNacimiento { get; set; }

        public int Nacionalidad { get; set; }
    
        public virtual Pais Pais { get; set; }
    }
}
